/* Generated by AN DISI Unibo */ 
package it.unibo.trolley

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Trolley ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				var CurrentStatus = "init"
				var OldStatus = "init"
				var Ticket = 0
				var Load = 0f
				
				var stopped : Boolean = false
				
				// gestione retry
				var retryCount = 0
				val MAX_RETRY = 3
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outmagenta("$name START ")
						CommUtils.outmagenta("$name engage BASIC ROBOT ")
						request("engage", "engage(trolley,160)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="waitrequest",cond=whenReply("engagedone"))
				}	 
				state("waitrequest") { //this:State
					action { //it:State
						if(  stopped  
						 ){ stopped = false  
						}
						 retryCount = 0  
						if( checkMsgContent( Term.createTerm("resumetrolley(X)"), Term.createTerm("resumetrolley(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name | RESUMED from STOP -> now operating in WAIT REQUEST...")
						}
						 
									OldStatus = CurrentStatus // salva stato precedente
									CurrentStatus = "waitrequest" 
						forward("setrobotstate", "setpos(0,0,down)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name | waiting for requests...")
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_waitrequest", 
				 	 					  scope, context!!, "local_tout_"+name+"_waitrequest", 600000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t010",targetState="exitsystem",cond=whenTimeout("local_tout_"+name+"_waitrequest"))   
					transition(edgeName="t011",targetState="gotoindoor",cond=whenDispatch("gotakecharge"))
					transition(edgeName="t012",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
					transition(edgeName="t013",targetState="handlereset",cond=whenDispatch("reset"))
				}	 
				state("gotoindoor") { //this:State
					action { //it:State
						if(  stopped  
						 ){ stopped = false  
						}
						if( checkMsgContent( Term.createTerm("resumetrolley(X)"), Term.createTerm("resumetrolley(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name | RESUMED from STOP -> now operating in GO TO INDOOR...")
						}
						 
									OldStatus = CurrentStatus
									CurrentStatus = "gotoindoor" 
						if( checkMsgContent( Term.createTerm("gotakecharge(X,Y)"), Term.createTerm("gotakecharge(TICKET,LOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name gotakecharge received -> moving to INDOOR")
								 
												Ticket = payloadArg(0).toInt()
												Load = payloadArg(1).toFloat() 
								CommUtils.outmagenta("$name taking charge - ticket n. $Ticket, $Load kg ")
						}
						delay(500) 
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="takeload",cond=whenReply("moverobotdone"))
					transition(edgeName="t015",targetState="failed",cond=whenReply("moverobotfailed"))
					transition(edgeName="t016",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
					transition(edgeName="t017",targetState="handlereset",cond=whenDispatch("reset"))
				}	 
				state("takeload") { //this:State
					action { //it:State
						if(  stopped  
						 ){ stopped = false  
						}
						if( checkMsgContent( Term.createTerm("resumetrolley(X)"), Term.createTerm("resumetrolley(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name | RESUMED from STOP -> now operating in TAKE LOAD...")
						}
						 
									OldStatus = CurrentStatus
									CurrentStatus = "takeload" 
						CommUtils.outmagenta("$name taking the load...")
						delay(2000) 
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_takeload", 
				 	 					  scope, context!!, "local_tout_"+name+"_takeload", 50.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t018",targetState="gotocoldroom",cond=whenTimeout("local_tout_"+name+"_takeload"))   
					transition(edgeName="t019",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
					transition(edgeName="t020",targetState="handlereset",cond=whenDispatch("reset"))
				}	 
				state("gotocoldroom") { //this:State
					action { //it:State
						if(  stopped  
						 ){ stopped = false  
						}
						if( checkMsgContent( Term.createTerm("resumetrolley(X)"), Term.createTerm("resumetrolley(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name | RESUMED from STOP -> now operating in GO TO COLDROOM...")
						}
						 
									OldStatus = CurrentStatus
									CurrentStatus = "gotocoldroom" 
									
						CommUtils.outmagenta("$name moving to COLDROOM")
						request("moverobot", "moverobot(4,3)" ,"basicrobot" )  
						delay(5000) 
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="storeload",cond=whenReply("moverobotdone"))
					transition(edgeName="t022",targetState="failed",cond=whenReply("moverobotfailed"))
					transition(edgeName="t023",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
					transition(edgeName="t024",targetState="handlereset",cond=whenDispatch("reset"))
				}	 
				state("storeload") { //this:State
					action { //it:State
						if(  stopped  
						 ){ stopped = false  
						}
						if( checkMsgContent( Term.createTerm("resumetrolley(X)"), Term.createTerm("resumetrolley(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name | RESUMED from STOP -> now operating in STORE LOAD...")
						}
						 
									OldStatus = CurrentStatus
									CurrentStatus = "storeload" 
						CommUtils.outmagenta("$name storing the load...")
						delay(500) 
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_storeload", 
				 	 					  scope, context!!, "local_tout_"+name+"_storeload", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t025",targetState="gohome",cond=whenTimeout("local_tout_"+name+"_storeload"))   
					transition(edgeName="t026",targetState="gotoindoor",cond=whenDispatch("gotakecharge"))
					transition(edgeName="t027",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
					transition(edgeName="t028",targetState="handlereset",cond=whenDispatch("reset"))
				}	 
				state("gohome") { //this:State
					action { //it:State
						if(  stopped  
						 ){ stopped = false  
						}
						if( checkMsgContent( Term.createTerm("resumetrolley(X)"), Term.createTerm("resumetrolley(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name | RESUMED from STOP -> now operating in GO HOME...")
						}
						 
									OldStatus = CurrentStatus
									CurrentStatus = "gohome" 
						CommUtils.outmagenta("$name going HOME...")
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						delay(2000) 
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_gohome", 
				 	 					  scope, context!!, "local_tout_"+name+"_gohome", 20000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t029",targetState="forcehome",cond=whenTimeout("local_tout_"+name+"_gohome"))   
					transition(edgeName="t030",targetState="trolleyathome",cond=whenReply("moverobotdone"))
					transition(edgeName="t031",targetState="verifyfailed",cond=whenReply("moverobotfailed"))
					transition(edgeName="t032",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
					transition(edgeName="t033",targetState="handlereset",cond=whenDispatch("reset"))
				}	 
				state("trolleyathome") { //this:State
					action { //it:State
						 
									OldStatus = CurrentStatus
									CurrentStatus = "trolleyathome" 
									retryCount = 0  // reset retry
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name | trolley at home")
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						CommUtils.outred("$name UPDATED RESOURCE statustrolley( $Ticket, $CurrentStatus )")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitrequest", cond=doswitch() )
				}	 
				state("forcehome") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | TIMEOUT gohome - forzo ritorno in HOME")
						 retryCount = retryCount + 1  
						if(  retryCount >= MAX_RETRY  
						 ){CommUtils.outred("$name | Troppi timeout, vado in waitrequest")
						}
						else
						 {forward("setdirection", "dir(down)" ,"basicrobot" ) 
						 delay(500) 
						 CommUtils.outyellow("$name | Riprovo a tornare in HOME (tentativo $retryCount)...")
						 request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_forcehome", 
				 	 					  scope, context!!, "local_tout_"+name+"_forcehome", 20000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t034",targetState="waitrequest",cond=whenTimeout("local_tout_"+name+"_forcehome"))   
					transition(edgeName="t035",targetState="trolleyathome",cond=whenReply("moverobotdone"))
					transition(edgeName="t036",targetState="verifyfailed",cond=whenReply("moverobotfailed"))
					transition(edgeName="t037",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
					transition(edgeName="t038",targetState="handlereset",cond=whenDispatch("reset"))
				}	 
				state("verifyfailed") { //this:State
					action { //it:State
						 retryCount = retryCount + 1  
						CommUtils.outmagenta("$name | gohome fallito (tentativo $retryCount/$MAX_RETRY)")
						if(  retryCount >= MAX_RETRY  
						 ){CommUtils.outred("$name | Troppi fallimenti gohome, accetto posizione corrente")
						 retryCount = 0  
						}
						else
						 {CommUtils.outyellow("$name | Riprovo gohome...")
						 forward("setdirection", "dir(down)" ,"basicrobot" ) 
						 delay(200) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_verifyfailed", 
				 	 					  scope, context!!, "local_tout_"+name+"_verifyfailed", 500.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t039",targetState="checkretry",cond=whenTimeout("local_tout_"+name+"_verifyfailed"))   
					transition(edgeName="t040",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
					transition(edgeName="t041",targetState="handlereset",cond=whenDispatch("reset"))
				}	 
				state("checkretry") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="gohome", cond=doswitchGuarded({ retryCount > 0  
					}) )
					transition( edgeName="goto",targetState="waitrequest", cond=doswitchGuarded({! ( retryCount > 0  
					) }) )
				}	 
				state("stoptrolley") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stoptrolley(X)"), Term.createTerm("stoptrolley(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  !stopped  
								 ){  
													stopped = true
													OldStatus = CurrentStatus
													CurrentStatus = "stopped" 
								CommUtils.outred("$name | STOP TROLLEY... previous state was $OldStatus, current state is $CurrentStatus")
								emit("alarm", "alarm(X)" ) 
								CommUtils.outred("$name | ALARM: STOP BASIC ROBOT... ")
								updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
								)
								}
								else
								 {CommUtils.outyellow("$name | STOP ignorato: il trolley è già  fermo")
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t042",targetState="waitrequest",cond=whenDispatchGuarded("resumetrolley",{ OldStatus == "waitrequest"  
					}))
					transition(edgeName="t043",targetState="gotoindoor",cond=whenDispatchGuarded("resumetrolley",{ OldStatus == "gotoindoor"  
					}))
					transition(edgeName="t044",targetState="takeload",cond=whenDispatchGuarded("resumetrolley",{ OldStatus == "takeload"  
					}))
					transition(edgeName="t045",targetState="gotocoldroom",cond=whenDispatchGuarded("resumetrolley",{ OldStatus == "gotocoldroom"  
					}))
					transition(edgeName="t046",targetState="storeload",cond=whenDispatchGuarded("resumetrolley",{ OldStatus == "storeload"  
					}))
					transition(edgeName="t047",targetState="gohome",cond=whenDispatchGuarded("resumetrolley",{ OldStatus == "gohome"  
					}))
					transition(edgeName="t048",targetState="waitrequest",cond=whenDispatch("resumetrolley"))
					transition(edgeName="t049",targetState="handlereset",cond=whenDispatch("reset"))
					transition(edgeName="t050",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
				}	 
				state("failed") { //this:State
					action { //it:State
						 retryCount = retryCount + 1  
						CommUtils.outmagenta("$name | $CurrentStatus failed -> tentativo $retryCount/$MAX_RETRY")
						if(  retryCount >= MAX_RETRY  
						 ){CommUtils.outred("$name | Troppi fallimenti, torno in waitrequest...")
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						delay(200) 
						 retryCount = 0  
						forward("giveup", "giveup(gohome)" ,"trolley" ) 
						}
						else
						 {CommUtils.outyellow("$name | Riprovo...")
						 if(  CurrentStatus == "gohome"  
						  ){CommUtils.outyellow("$name | $CurrentStatus -> correggo orientamento prima di riprovare...")
						 forward("setdirection", "dir(down)" ,"basicrobot" ) 
						 delay(200) 
						 }
						 forward("tryagain", "tryagain(retry)" ,"trolley" ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t051",targetState="gohome",cond=whenDispatch("giveup"))
					transition(edgeName="t052",targetState="gotoindoor",cond=whenDispatchGuarded("tryagain",{ CurrentStatus == "gotoindoor"  
					}))
					transition(edgeName="t053",targetState="gotocoldroom",cond=whenDispatchGuarded("tryagain",{ CurrentStatus == "gotocoldroom"  
					}))
					transition(edgeName="t054",targetState="gohome",cond=whenDispatchGuarded("tryagain",{ CurrentStatus == "gohome"  
					}))
					transition(edgeName="t055",targetState="waitrequest",cond=whenDispatch("tryagain"))
					transition(edgeName="t056",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
				}	 
				state("handlereset") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("reset(X)"), Term.createTerm("reset(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name | ricevuto comando RESET: ${payloadArg(0)} ...")
								 
								            	OldStatus = CurrentStatus
								            	CurrentStatus = "handlereset"
								            	retryCount = 0  // reset retry
								updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
								)
								if(  stopped  
								 ){ stopped = false  
								CommUtils.outmagenta("$name | Il robot era fermo, ora riparte!")
								}
								CommUtils.outmagenta("$name | RESET: correggo orientamento...")
								forward("setdirection", "dir(down)" ,"basicrobot" ) 
								delay(500) 
								CommUtils.outmagenta("$name | RESET: il robot va in HOME")
								request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handlereset", 
				 	 					  scope, context!!, "local_tout_"+name+"_handlereset", 20000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t057",targetState="resetdone",cond=whenTimeout("local_tout_"+name+"_handlereset"))   
					transition(edgeName="t058",targetState="resetdone",cond=whenReply("moverobotdone"))
					transition(edgeName="t059",targetState="resetretry",cond=whenReply("moverobotfailed"))
					transition(edgeName="t060",targetState="stoptrolley",cond=whenDispatch("stoptrolley"))
				}	 
				state("resetdone") { //this:State
					action { //it:State
						 
									OldStatus = CurrentStatus
									CurrentStatus = "resetdone"
									
							        Ticket = 0
							        Load = 0f
							        retryCount = 0
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name | Reset completato, il robot è in HOME")
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						CommUtils.outred("$name UPDATED RESOURCE statustrolley( $Ticket, $CurrentStatus )")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitrequest", cond=doswitch() )
				}	 
				state("resetretry") { //this:State
					action { //it:State
						 retryCount = retryCount + 1  
						CommUtils.outmagenta("$name | Reset fallito (tentativo $retryCount)...")
						if(  retryCount >= 3  
						 ){CommUtils.outred("$name | Troppi tentativi di reset falliti, forzo il robot a tornare in HOME...")
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						delay(1000) 
						 
								        OldStatus = CurrentStatus
								        CurrentStatus = "resetdone"
								        Ticket = 0
								        Load = 0f 
								        retryCount = 0 
						updateResourceRep( "statustrolley( $Ticket, $CurrentStatus )"  
						)
						CommUtils.outred("$name | Troppi fallimenti, vado in waitrequest dalla posizione corrente...")
						}
						else
						 {CommUtils.outmagenta("$name | Reset fallito, riprovo (tentativo $retryCount)...")
						 delay(1000) 
						 forward("reset", "reset(retry)" ,"trolley" ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitrequest", cond=doswitchGuarded({ retryCount == 0  
					}) )
					transition( edgeName="goto",targetState="handlereset", cond=doswitchGuarded({! ( retryCount == 0  
					) }) )
				}	 
				state("exitsystem") { //this:State
					action { //it:State
						forward("disengage", "disengage(trolley)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name  disengaged")
						delay(1000) 
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
