/* Generated by AN DISI Unibo */ 
package it.unibo.trolley

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Trolley ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				var Status = "init"
				var Ticket = 0
				var Load = 0f
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						updateResourceRep( "statustrolley( $Ticket, $Status )"  
						)
						CommUtils.outred("$name UPDATED RESOURCE statustrolley( $Ticket, $Status )")
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outmagenta("$name START ")
						CommUtils.outmagenta("$name engage BASIC ROBOT ")
						request("engage", "engage(trolley,150)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="waitrequest",cond=whenReply("engagedone"))
				}	 
				state("waitrequest") { //this:State
					action { //it:State
						forward("setrobotstate", "setpos(0,0,down)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name waiting for requests...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="gotoindoor",cond=whenDispatch("gotakecharge"))
				}	 
				state("gotoindoor") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name moving to INDOOR")
						if( checkMsgContent( Term.createTerm("gotakecharge(X,Y)"), Term.createTerm("gotakecharge(TICKET,LOAD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												Ticket = payloadArg(0).toInt()
												Load = payloadArg(1).toFloat() 
								CommUtils.outmagenta("$name taking charge - ticket n. $Ticket, $Load kg ")
						}
						delay(500) 
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="takeload",cond=whenReply("moverobotdone"))
					transition(edgeName="t010",targetState="failed",cond=whenReply("moverobotfailed"))
				}	 
				state("takeload") { //this:State
					action { //it:State
						 Status = "takeload"  
						CommUtils.outmagenta("$name taking the load...")
						delay(500) 
						updateResourceRep( "statustrolley( $Ticket, $Status )"  
						)
						CommUtils.outred("$name UPDATED RESOURCE statustrolley( $Ticket, $Status )")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="gotocoldroom", cond=doswitch() )
				}	 
				state("gotocoldroom") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name moving to COLDROOM")
						request("moverobot", "moverobot(4,3)" ,"basicrobot" )  
						delay(5000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="storeload",cond=whenReply("moverobotdone"))
					transition(edgeName="t012",targetState="failed",cond=whenReply("moverobotfailed"))
				}	 
				state("storeload") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name storing the load...")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_storeload", 
				 	 					  scope, context!!, "local_tout_"+name+"_storeload", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t013",targetState="gohome",cond=whenTimeout("local_tout_"+name+"_storeload"))   
					transition(edgeName="t014",targetState="gotoindoor",cond=whenDispatch("gotakecharge"))
				}	 
				state("gohome") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name going HOME...")
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="trolleyathome",cond=whenReply("moverobotdone"))
					transition(edgeName="t016",targetState="failed",cond=whenReply("moverobotfailed"))
				}	 
				state("trolleyathome") { //this:State
					action { //it:State
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name trolley at home")
						forward("disengage", "disengage(trolley)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name  disengaged")
						delay(1000) 
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("failed") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name action failed")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="gohome", cond=doswitch() )
				}	 
			}
		}
} 
