/* Generated by AN DISI Unibo */ 
package it.unibo.trolley

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Trolley ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outmagenta("$name START ")
						CommUtils.outmagenta("$name engage BASIC ROBOT ")
						request("engage", "engage(trolley,150)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="waitrequest",cond=whenReply("engagedone"))
				}	 
				state("waitrequest") { //this:State
					action { //it:State
						forward("setrobotstate", "setpos(0,0,down)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name waiting for requests...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="gotoindoor",cond=whenDispatch("gotakecharge"))
				}	 
				state("gotoindoor") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("gotakecharge(X)"), Term.createTerm("gotakecharge(TICKET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outmagenta("$name moving to INDOOR")
						}
						delay(500) 
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="takeload",cond=whenReply("moverobotdone"))
					transition(edgeName="t09",targetState="failed",cond=whenReply("moverobotfailed"))
				}	 
				state("takeload") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name taking the load...")
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="gotocoldroom", cond=doswitch() )
				}	 
				state("gotocoldroom") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name moving to COLDROOM")
						request("moverobot", "moverobot(4,3)" ,"basicrobot" )  
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="storeload",cond=whenReply("moverobotdone"))
					transition(edgeName="t011",targetState="failed",cond=whenReply("moverobotfailed"))
				}	 
				state("storeload") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name storing the load...")
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_storeload", 
				 	 					  scope, context!!, "local_tout_"+name+"_storeload", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t012",targetState="gohome",cond=whenTimeout("local_tout_"+name+"_storeload"))   
					transition(edgeName="t013",targetState="gotoindoor",cond=whenDispatch("gotakecharge"))
				}	 
				state("gohome") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name going HOME...")
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="trolleyathome",cond=whenReply("moverobotdone"))
					transition(edgeName="t015",targetState="failed",cond=whenReply("moverobotfailed"))
				}	 
				state("trolleyathome") { //this:State
					action { //it:State
						forward("setrobotstate", "setpos(0,0,down)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name trolley at home")
						forward("disengage", "disengage(trolley)" ,"basicrobot" ) 
						CommUtils.outmagenta("$name  disengaged")
						delay(1000) 
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("failed") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name moverobot to indoor failed")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
